name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests

      - name: Deploy to test environment
        run: |
          # Add your deployment commands here

      - name: Send email notification (optional)
        uses: softprops/action-gh-release@v1
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Notification"
          body: "The workflow has completed."
          to: ${{ secrets.EMAIL_ADDRESS }}
